name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: windows-latest

    env:
      PROJECT_PATH: 'src/TinyTrophy.csproj' 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Publish the application
    - name: Publish application
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./publish

    # Upload the entire publish folder containing the .exe and required files
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Published-App
        path: ./publish/*.exe
